feat: update devcontainer configuration and add J-Link support

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -14,7 +14,15 @@ RUN if [ "${REINSTALL_CMAKE_VERSION_FROM_SOURCE}" != "none" ]; then \
 # RUN su vscode -c "${VCPKG_ROOT}/vcpkg install <your-port-name-here>"
 
 # [Optional] Uncomment this section to install additional packages.
-# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-#     && apt-get -y install --no-install-recommends <your-package-list-here>
+RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -y install --no-install-recommends usbutils gcc-arm-none-eabi gdb-arm-none-eabi \
+    && apt-get clean
 
-RUN apt update && apt install -y gcc-arm-none-eabi gdb-arm-none-eabi
+# Install the JLink package from host machine
+# Copy the JLink .deb file into the container
+COPY ./JLink_Linux_V824_x86_64.deb /tmp/
+RUN dpkg --unpack /tmp/JLink_Linux_V824_x86_64.deb
+RUN rm /var/lib/dpkg/info/jlink.postinst -f
+# dpkg configure, if it fails, ignore the error
+RUN dpkg --configure jlink || true
+RUN apt install -yf 
